 
 /*------------------------------------------------------------------------
    File        : Empty_UT
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Tue Jul 02 14:48:23 CEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

class test.Empty_UT: 
  
  @test.
  method public void dummy_test(). end.
  
end class.