
/*------------------------------------------------------------------------
    File        : ParameterType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Tue Jul 16 15:21:35 CEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

enum core.openapi.OpenApiParameterType :  

  define enum 
    Path 
    Query 
    Header 
    Cookie 
    .

end enum.
